version: '3'
services:

  video-streaming:
    image: video-streaming
    build:
      context: ./projects/video-streaming
      # dockerfile: Dockerfile-dev
    container_name: video-streaming
    volumes:
      - /tmp/video-streaming/npm-cache:/root/.npm:z
      - ./projects/video-streaming/src:/usr/src/app/src:z
      - ./projects/video-streaming/assets:/usr/src/app/assets:z
    ports:
      - "4000:80"
    environment:
      - PORT=80
      - NODE_ENV=development
    restart: "no"

  video-history:
    image: video-history
    build:
      context: ./projects/video-history
      dockerfile: Dockerfile-dev
    container_name: video-history
    volumes:
      - /tmp/video-history/npm-cache:/root/.npm:z # share dep.
      - ./projects/video-history/src:/usr/src/app/src:z  # share src code
    ports:
      - "4001:80"
    environment:
      - PORT=80
      - NODE_ENV=development
    restart: "no"
