version: '3'
services:

  video-streaming:
    image: video-streaming
    build: 
      context: ./projects/video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
     - "4000:80"
    environment:
      - PORT=80
    restart: "no" # don't auto restart on crash