version: '3'
services:

  db:
    image: mongo:5.0.9
    container_name: db
    ports:
      - "4000:27017"
    restart: always

  rabbit:
    image: rabbitmq:3.9.21-management
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
      - "15672"
    restart: always

  video-streaming:
    image: video-streaming
    build: 
      context: ./projects/video-streaming
      dockerfile: Dockerfile-dev
    container_name: video-streaming
    volumes:
      - /tmp/video-streaming/npm-cache:/root/.npm:z
      - ./projects/video-streaming/src:/usr/src/app/src:z
      - ./projects/video-streaming/assets:/usr/src/app/assets:z
    ports:
      - "4001:80"
    environment:
      - PORT=80
      - RABBIT=amqp://guest:guest@rabbit:5672
      - NODE_ENV=development
    depends_on:
      - rabbit
    restart: "no"

  video-history:
    image: video-history
    build: 
      context: ./projects/video-history
      dockerfile: Dockerfile-dev
    container_name: video-history
    volumes:
      - /tmp/video-history/npm-cache:/root/.npm:z # share dep.
      - ./projects/video-history/src:/usr/src/app/src:z  # share src code
    ports:
     - "4002:80"
    environment:
      - PORT=80
      - RABBIT=amqp://guest:guest@rabbit:5672
      - DBHOST=mongodb://db:27017
      - DBNAME=history
      - NODE_ENV=development
    depends_on:
      - db
      - rabbit
    restart: "no"